### PR TITLE
Added Comments

### PR DESCRIPTION
**Pull request by johnstev111**
You're welcome.
Also it's good practice to distinguish C `.h` files and C++ `.hpp` files.
Added a sample logo? Idea would be to use IBM Plex Mono as the font because it's a language, and at font-weight 700.

### CODE REVIEW

**Comment by johnstev111** [comment]
@DynamicSquid What do you think?

**Comment by DynamicSquid** [comment]
Thank you!!! A few things...

> Also it's good practice to distinguish C .h files and C++ .hpp files.

Oh yeah, ik. I'm just putting everything into one file one since it's just easier for me to maintain (I actually don't like switching between files that much). I'll separate them in the future.

> A (interpreted?)
> An (interpreted?)

I'm not really sure about brackets and grammar, but I'll take your word

> How about .n?

Hmm... that seems a little too short... I tried `.night`, but that's a little long. `.ngt` is also good, but I think it can be better. Don't worry though, I'll have plenty of time to think about this in the future

> // error! also comments now work!

Yup!! I forgot to update the README file when I did my code

> 	if (token == "bool") {
>		tokens.push_back(Token{ TokenTypes::BOOL_TYPE, "bool" });
>		token = "";
>	}

No. There must be a space. ALWAYS A SPACUEWBUFG KSJ lol

> Ad-ed logo

That actually does seem cool. I might actually use MS paint to create my logo. Right now, my strategy is to just use Processing. I updated a new logo in `logo2.png`. I'm still working on the design though. I'll still have plenty of time to make on in the future though


Thanks!!!!!

**Comment by johnstev111** [comment]
Okay! You can merge the pull request, if you like. 😄

**Comment by DynamicSquid** [comment]
Oh just a note, I'll update this project afternoon today. They'll be some big changes

**Comment by johnstev111** [comment]
Oh... Interesting!

**Comment by DynamicSquid** [comment]
Oh, I don't want to merge everything just yet. i'll still keep your files them though

**Comment by johnstev111** [comment]
Ok! I'll work on the conversion library

**Comment by DynamicSquid** [comment]
Oooh... i like it! Well done!!!!

**Comment by johnstev111** [comment]
@DynamicSquid No conversions: casts only. They're done

**Comment by johnstev111** [comment]
Goodnight, I'll be going to sleep. See you tomorrow! (at the time you wake up, which is 4-5pm my time)

**Comment by johnstev111** [comment]
I'm leaving the night project. Keep the code.

**Comment by johnstev111** [comment]
@DynamicSquid I don't think you need to be writnig this.... have you considered lex and yacc (flex and bison)?

**Pull request closed without merging**
