### PR TITLE
Better Readme

### PR DESCRIPTION
**Pull request by AntimatterReactor**
Better Readme Structure, Added Version History, Planning to add a wiki.

### CODE REVIEW

**Comment by DynamicSquid** [comment]
I fixed up the readme file and included some of your changes. any improvements?

**Comment by AntimatterReactor** [comment]
probably just table of contents, comparison, and wiki, but, that's good enough.

**Comment by AntimatterReactor** [comment]
> I fixed up the readme file and included some of your changes. any improvements?

not much actually

**Comment by DynamicSquid** [comment]
the wiki will be on the website, and I'll add a table of contents tmr if that's fine cause l'm really busy rn, thanks for the suggestions though!!

**Pull request closed without merging**
