### PR TITLE
Fix build errors

### PR DESCRIPTION
**Pull request by CodeLongAndProsper90**
Fix build errors with g++ related to header files, PKGBUILD for AUR planned and Makefile WIP.

### CODE REVIEW

**Comment by DynamicSquid** [comment]
oh ok cool! did you test it with g++ yet?

**Comment by CodeLongAndProsper90** [comment]
Yeah, I compiled it. There was some stuff like Lexer.h being included as Lexer.h that I fixed.

**Comment by DynamicSquid** [comment]
oh okay nice! quick question though, how do you compile it? cause there's a makefile in there and I'm not sure what do do about that... or did you not compiled the makefile and you just compiled the source files?

**Comment by DynamicSquid** [comment]
oh wow that's awesome! I just compiled it and it worked (aside from some few warning which I can fix)! thank you!!

**Comment by CodeLongAndProsper90** [comment]
Oh btw I think the default target is just all, so `make` to compile it.

**Pull request merged**
