### PR TITLE
Added Makefile and link to dusk

### PR DESCRIPTION
**Pull request by firefish111**
# Hello!
***
Just trying to make things easier!
I added a link to dusk and a Makefile =)

### CODE REVIEW

**Comment by firefish111** [comment]
@DynamicSquid Would this be a good idea? If you want to I can add the preprocessor...

**Comment by DynamicSquid** [comment]
that'd be awesome!

**Comment by firefish111** [comment]
@DynamicSquid Well, as the old saying goes,
> it's easier to understand your own code than someone else's

~~also the github CLI is useful, I made this pull request in it~~

**Comment by DynamicSquid** [comment]
~~what's a github cli? also what does the makefile do?~~

oh, wanna help me test v3.0?

**Comment by firefish111** [comment]
Yep, sure

**Comment by DynamicSquid** [comment]
k, lemme push it to repl gimme a sec

**Comment by DynamicSquid** [comment]
sorry that took a while I invited you

**Comment by firefish111** [comment]
@DynamicSquid Are you alright with the import syntax `use example;`, or what keyword should I use?

**Comment by firefish111** [comment]
@DynamicSquid resolved conflicts! You can now merge, and the pre-processor is done

**Comment by firefish111** [comment]
Well it's fine if there are conflicts they're not that hard to resolve @DynamicSquid

**Comment by firefish111** [comment]
@DynamicSquid May I ask, will the code form this now closed pull request, be re-implemented into your target v3.3?

**Comment by firefish111** [comment]
@CodeLongAndProsper90 Here is pr 28

**Pull request closed without merging**
