### PR TITLE
Fixed bunch of things on website

### PR DESCRIPTION
**Pull request by AntimatterReactor**
Basically, I removed the stars background gradient because it cause lag. I also corrected learn.html formatting. I also make the navigation button more mobile friendly. I also revamped the tutorial, you might need to fact check this one. And I also fixed typos in timeline.md and filled in apache lisence's placeholders

### CODE REVIEW

**Comment by AntimatterReactor** [comment]
God, these checks are redundant and broken. @DynamicSquid I mean, what's the reason you keep it anyway? Just askin', maybe I could fix it if I try hard enough

**Comment by DynamicSquid** [comment]
Yeah, sorry for the CI. I hate it too. I'm still trying to fix it but I have no clue what I'm doing. Just ignore it for now.

And for your PR, I don't have much time now, but I'll take a look at it later today.

Thanks!

**Comment by AntimatterReactor** [comment]
Ok, umm:

1a. On the js files i mostly just remove the gradient background / commented it to reduce lag.

1b. I've also changed the install.js triangle thing to just run as a draw function instead of onclick one by just borrowing things from the index.js.

1c. On the css file i've made <code> blocks in the learn page more purple-ish. 

1d. I've also change codeblocks or <p class="code"> and <code>'s font to fira code, mostly just for the linting thing or something.

1e. I've also make all <a> links to become slightly darker once visited.

1f. I've also make the stars blink more subtly by making the brightness value on the constructor to be random(255,255).

2a. I've changed the main menu nav button thing to be the same accross all page and just change color on the button of the same page (pending, I haven't committed this)

2b. I've also changed the nav menu to <p> instead of <h2> so i can adjust the size more finely to be friendly to mobile.

2c. I've also corrected the whole learn page to be visible and to have the same code formating thing as the index page. And to also have the same text formatting as the other page.

2d. I've also edited the tutorial to be more accurate now.

2e. I've also fixed some broken github link.

3a. I've fixed typos on the timeline.md

3b. I've also add the .md extension to LICENSE and fill in info on the placeholders

4. I've added quote on .travis yml CXX=... thing that is causing error or something.

And yeah, a lot of this are particularly done badly. But heyit works!

**Comment by DynamicSquid** [comment]
Oh, I meant split up your PR as in create 4 separate PRs :)

That way we can review and merge PRs individually, without effecting the others.

Sorry for the confusion

**Comment by AntimatterReactor** [comment]
ok

**Pull request closed without merging**
